// Generated by gencpp from file krti2024_pi/Activate.msg
// DO NOT EDIT!


#ifndef KRTI2024_PI_MESSAGE_ACTIVATE_H
#define KRTI2024_PI_MESSAGE_ACTIVATE_H

#include <ros/service_traits.h>


#include <krti2024_pi/ActivateRequest.h>
#include <krti2024_pi/ActivateResponse.h>


namespace krti2024_pi
{

struct Activate
{

typedef ActivateRequest Request;
typedef ActivateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Activate
} // namespace krti2024_pi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::krti2024_pi::Activate > {
  static const char* value()
  {
    return "62bff225506042c8c22b370ac260f09e";
  }

  static const char* value(const ::krti2024_pi::Activate&) { return value(); }
};

template<>
struct DataType< ::krti2024_pi::Activate > {
  static const char* value()
  {
    return "krti2024_pi/Activate";
  }

  static const char* value(const ::krti2024_pi::Activate&) { return value(); }
};


// service_traits::MD5Sum< ::krti2024_pi::ActivateRequest> should match
// service_traits::MD5Sum< ::krti2024_pi::Activate >
template<>
struct MD5Sum< ::krti2024_pi::ActivateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::krti2024_pi::Activate >::value();
  }
  static const char* value(const ::krti2024_pi::ActivateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::krti2024_pi::ActivateRequest> should match
// service_traits::DataType< ::krti2024_pi::Activate >
template<>
struct DataType< ::krti2024_pi::ActivateRequest>
{
  static const char* value()
  {
    return DataType< ::krti2024_pi::Activate >::value();
  }
  static const char* value(const ::krti2024_pi::ActivateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::krti2024_pi::ActivateResponse> should match
// service_traits::MD5Sum< ::krti2024_pi::Activate >
template<>
struct MD5Sum< ::krti2024_pi::ActivateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::krti2024_pi::Activate >::value();
  }
  static const char* value(const ::krti2024_pi::ActivateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::krti2024_pi::ActivateResponse> should match
// service_traits::DataType< ::krti2024_pi::Activate >
template<>
struct DataType< ::krti2024_pi::ActivateResponse>
{
  static const char* value()
  {
    return DataType< ::krti2024_pi::Activate >::value();
  }
  static const char* value(const ::krti2024_pi::ActivateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KRTI2024_PI_MESSAGE_ACTIVATE_H
