// Generated by gencpp from file krti2024_pi/ActivateRequest.msg
// DO NOT EDIT!


#ifndef KRTI2024_PI_MESSAGE_ACTIVATEREQUEST_H
#define KRTI2024_PI_MESSAGE_ACTIVATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krti2024_pi
{
template <class ContainerAllocator>
struct ActivateRequest_
{
  typedef ActivateRequest_<ContainerAllocator> Type;

  ActivateRequest_()
    : data(false)
    , target(0)  {
    }
  ActivateRequest_(const ContainerAllocator& _alloc)
    : data(false)
    , target(0)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;

   typedef uint8_t _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::krti2024_pi::ActivateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krti2024_pi::ActivateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActivateRequest_

typedef ::krti2024_pi::ActivateRequest_<std::allocator<void> > ActivateRequest;

typedef boost::shared_ptr< ::krti2024_pi::ActivateRequest > ActivateRequestPtr;
typedef boost::shared_ptr< ::krti2024_pi::ActivateRequest const> ActivateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krti2024_pi::ActivateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krti2024_pi::ActivateRequest_<ContainerAllocator1> & lhs, const ::krti2024_pi::ActivateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krti2024_pi::ActivateRequest_<ContainerAllocator1> & lhs, const ::krti2024_pi::ActivateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krti2024_pi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti2024_pi::ActivateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti2024_pi::ActivateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti2024_pi::ActivateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae203cc5a016563f8b7bf347774c2587";
  }

  static const char* value(const ::krti2024_pi::ActivateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae203cc5a016563fULL;
  static const uint64_t static_value2 = 0x8b7bf347774c2587ULL;
};

template<class ContainerAllocator>
struct DataType< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krti2024_pi/ActivateRequest";
  }

  static const char* value(const ::krti2024_pi::ActivateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# this .srv needed for \n"
"\n"
"# activating target detection under '/vision/activate/target'\n"
"\n"
"bool data\n"
"uint8 target\n"
;
  }

  static const char* value(const ::krti2024_pi::ActivateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krti2024_pi::ActivateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krti2024_pi::ActivateRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
    s << indent << "target: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRTI2024_PI_MESSAGE_ACTIVATEREQUEST_H
