// Generated by gencpp from file krti2024_pi/ActivateResponse.msg
// DO NOT EDIT!


#ifndef KRTI2024_PI_MESSAGE_ACTIVATERESPONSE_H
#define KRTI2024_PI_MESSAGE_ACTIVATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krti2024_pi
{
template <class ContainerAllocator>
struct ActivateResponse_
{
  typedef ActivateResponse_<ContainerAllocator> Type;

  ActivateResponse_()
    : result(false)  {
    }
  ActivateResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::krti2024_pi::ActivateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krti2024_pi::ActivateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ActivateResponse_

typedef ::krti2024_pi::ActivateResponse_<std::allocator<void> > ActivateResponse;

typedef boost::shared_ptr< ::krti2024_pi::ActivateResponse > ActivateResponsePtr;
typedef boost::shared_ptr< ::krti2024_pi::ActivateResponse const> ActivateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krti2024_pi::ActivateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krti2024_pi::ActivateResponse_<ContainerAllocator1> & lhs, const ::krti2024_pi::ActivateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krti2024_pi::ActivateResponse_<ContainerAllocator1> & lhs, const ::krti2024_pi::ActivateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krti2024_pi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti2024_pi::ActivateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti2024_pi::ActivateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti2024_pi::ActivateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::krti2024_pi::ActivateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krti2024_pi/ActivateResponse";
  }

  static const char* value(const ::krti2024_pi::ActivateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result \n"
;
  }

  static const char* value(const ::krti2024_pi::ActivateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krti2024_pi::ActivateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krti2024_pi::ActivateResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRTI2024_PI_MESSAGE_ACTIVATERESPONSE_H
