// Generated by gencpp from file krti2024_pi/DResult.msg
// DO NOT EDIT!


#ifndef KRTI2024_PI_MESSAGE_DRESULT_H
#define KRTI2024_PI_MESSAGE_DRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krti2024_pi
{
template <class ContainerAllocator>
struct DResult_
{
  typedef DResult_<ContainerAllocator> Type;

  DResult_()
    : is_found(false)
    , dx(0)
    , dy(0)
    , dx_m(0.0)
    , dy_m(0.0)  {
    }
  DResult_(const ContainerAllocator& _alloc)
    : is_found(false)
    , dx(0)
    , dy(0)
    , dx_m(0.0)
    , dy_m(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _is_found_type;
  _is_found_type is_found;

   typedef int32_t _dx_type;
  _dx_type dx;

   typedef int32_t _dy_type;
  _dy_type dy;

   typedef float _dx_m_type;
  _dx_m_type dx_m;

   typedef float _dy_m_type;
  _dy_m_type dy_m;





  typedef boost::shared_ptr< ::krti2024_pi::DResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krti2024_pi::DResult_<ContainerAllocator> const> ConstPtr;

}; // struct DResult_

typedef ::krti2024_pi::DResult_<std::allocator<void> > DResult;

typedef boost::shared_ptr< ::krti2024_pi::DResult > DResultPtr;
typedef boost::shared_ptr< ::krti2024_pi::DResult const> DResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krti2024_pi::DResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krti2024_pi::DResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krti2024_pi::DResult_<ContainerAllocator1> & lhs, const ::krti2024_pi::DResult_<ContainerAllocator2> & rhs)
{
  return lhs.is_found == rhs.is_found &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dx_m == rhs.dx_m &&
    lhs.dy_m == rhs.dy_m;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krti2024_pi::DResult_<ContainerAllocator1> & lhs, const ::krti2024_pi::DResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krti2024_pi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krti2024_pi::DResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti2024_pi::DResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti2024_pi::DResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti2024_pi::DResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti2024_pi::DResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti2024_pi::DResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krti2024_pi::DResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdb57b108ed455ecab1cab6b0ba9017d";
  }

  static const char* value(const ::krti2024_pi::DResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdb57b108ed455ecULL;
  static const uint64_t static_value2 = 0xab1cab6b0ba9017dULL;
};

template<class ContainerAllocator>
struct DataType< ::krti2024_pi::DResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krti2024_pi/DResult";
  }

  static const char* value(const ::krti2024_pi::DResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krti2024_pi::DResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_found\n"
"int32 dx\n"
"int32 dy\n"
"float32 dx_m\n"
"float32 dy_m\n"
;
  }

  static const char* value(const ::krti2024_pi::DResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krti2024_pi::DResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_found);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dx_m);
      stream.next(m.dy_m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krti2024_pi::DResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krti2024_pi::DResult_<ContainerAllocator>& v)
  {
    s << indent << "is_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_found);
    s << indent << "dx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dy);
    s << indent << "dx_m: ";
    Printer<float>::stream(s, indent + "  ", v.dx_m);
    s << indent << "dy_m: ";
    Printer<float>::stream(s, indent + "  ", v.dy_m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRTI2024_PI_MESSAGE_DRESULT_H
