# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from krti2024_pi/DResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DResult(genpy.Message):
  _md5sum = "bdb57b108ed455ecab1cab6b0ba9017d"
  _type = "krti2024_pi/DResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool is_found
int32 dx
int32 dy
float32 dx_m
float32 dy_m"""
  __slots__ = ['is_found','dx','dy','dx_m','dy_m']
  _slot_types = ['bool','int32','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_found,dx,dy,dx_m,dy_m

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.is_found is None:
        self.is_found = False
      if self.dx is None:
        self.dx = 0
      if self.dy is None:
        self.dy = 0
      if self.dx_m is None:
        self.dx_m = 0.
      if self.dy_m is None:
        self.dy_m = 0.
    else:
      self.is_found = False
      self.dx = 0
      self.dy = 0
      self.dx_m = 0.
      self.dy_m = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2i2f().pack(_x.is_found, _x.dx, _x.dy, _x.dx_m, _x.dy_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.is_found, _x.dx, _x.dy, _x.dx_m, _x.dy_m,) = _get_struct_B2i2f().unpack(str[start:end])
      self.is_found = bool(self.is_found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2i2f().pack(_x.is_found, _x.dx, _x.dy, _x.dx_m, _x.dy_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.is_found, _x.dx, _x.dy, _x.dx_m, _x.dy_m,) = _get_struct_B2i2f().unpack(str[start:end])
      self.is_found = bool(self.is_found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2i2f = None
def _get_struct_B2i2f():
    global _struct_B2i2f
    if _struct_B2i2f is None:
        _struct_B2i2f = struct.Struct("<B2i2f")
    return _struct_B2i2f
